import { Button, VerticalBox , AboutSlint } from "std-widgets.slint";
import { ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 320px;
    height: 240px;
    in-out property<int> counter: 42;
    callback request-increase-value();
    in-out property<float> scroll_offset: 0; // Vị trí cuộn (pixel)
    VerticalBox { 
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }

        ScrollView {
            viewport-height: 600px;
            width: parent.width;
            height: parent.height - 100px; // Điều chỉnh để chiếm không gian còn lại
            viewport-y: -root.scroll_offset * 1px; // Đồng bộ với offset cuộn
            
            VerticalLayout {
                spacing: 10px;
                for i in 20 : Rectangle {
                    height: 50px;
                    background: #ff0000;
                    Text {
                        text: "Item " + i;
                        color: #ffffff;
                    }
                }
            }
        }
     }
}
